---
language: shell
os: linux
dist: bionic

services:
  - docker
before_install:
  - 'docker pull aminvakil/archlinux:devel'
script:
  - 'container_id=$(mktemp)'
  - 'docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/aur aminvakil/archlinux:devel > "${container_id}"'
  - 'docker exec "$(cat ${container_id})" pacman -Suy --noconfirm'
  - 'docker exec "$(cat ${container_id})" su devel sh -c "sudo id && id"'
  - 'docker rm -f "$(cat ${container_id})"'
