---
language: shell
os: linux
dist: bionic

services:
  - docker
before_install:
  - 'docker pull archlinux'
  - 'docker build --no-cache --rm --file=travis/Dockerfile --tag=archlinux:devel travis'
script:
  - 'container_id=$(mktemp)'
  - 'docker run --detach --volume="${PWD}":/aur archlinux:devel > "${container_id}"'
  - 'docker exec "$(cat ${container_id})" "cd aur/assetfinder && makepkg -s"'
  - 'docker rm -f "$(cat ${container_id})"'
