---
language: shell
os: linux
dist: bionic
env:
  - pkg: assetfinder
  - pkg: assetfinder-git
  - pkg: fcct-bin
  - pkg: gnome-shell-extension-public-ip-git
  - pkg: gnome-shell-extension-workspace-matrix
  - pkg: google-tsunami-security-scanner
  - pkg: google-tsunami-security-scanner-git
  - pkg: google-tsunami-security-scanner-plugins-git
  - pkg: jmeter-plugins-manager
  - pkg: obfs4proxy-behind-tor
  - pkg: tor-browser-behind-tor
  - pkg: xssmap

services:
  - docker
before_install:
  - docker pull aminvakil/archlinux:devel
before_script:
  #  - changed_pkg=$(git diff --name-only HEAD HEAD~1 | cut -d "/" -f1)
  #  - changed_pkg="fcct-bin"
  - if [ ! -d "${pkg}" ]; then exit 0; fi
script:
  - container_id=$(mktemp)
  - docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}/${pkg}":/pkg aminvakil/archlinux:devel > "${container_id}"
  - if [ -f travis/"${pkg}"/before_makepkg.sh ]; then docker exec -i "$(cat ${container_id})" sh < travis/"${pkg}"/before_makepkg.sh; fi
  - docker exec "$(cat ${container_id})" pacman -Suy --noconfirm
  - 'docker exec "$(cat ${container_id})" chown -R devel: /pkg'
  - docker exec "$(cat ${container_id})" su devel sh -c "cd /pkg && makepkg -sri --noconfirm"
  - docker rm -f "$(cat ${container_id})"
