---
language: shell
os: linux
dist: bionic

services:
  - docker
before_install:
  - 'docker pull aminvakil/archlinux:devel'
script:
  - 'container_id=$(mktemp)'
  - 'changed_pkg=$(git diff --name-only HEAD HEAD~1 | cut -d "/" -f1)'
  - 'docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}/${changed_pkg}":/aur aminvakil/archlinux:devel > "${container_id}"'
  - '[ -f "${changed_pkg}" ] && docker exec "$(cat ${container_id})" sh < travis/"${changed_pkg}"/before_makepkg.sh'
  - 'docker exec "$(cat ${container_id})" pacman -Suy --noconfirm'
  - 'docker exec "$(cat ${container_id})" chown -R devel: /aur'
  - 'docker exec "$(cat ${container_id})" su devel sh -c "cd /aur && makepkg -sri --noconfirm"'
  - 'docker rm -f "$(cat ${container_id})"'
