---
language: shell
os: linux
dist: bionic

services:
  - docker
before_install:
  - docker pull aminvakil/archlinux:devel
before_script:
  - changed_pkg=$(git diff --name-only HEAD HEAD~1 | cut -d "/" -f1)
  - if [ ! -d "${changed_pkg}" ]; then exit 0; fi
script:
  - container_id=$(mktemp)
  - docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}/${changed_pkg}":/aur aminvakil/archlinux:devel > "${container_id}"
  - if [ -f travis/"${changed_pkg}"/before_makepkg.sh ]; then docker exec "$(cat ${container_id})" sh < travis/"${changed_pkg}"/before_makepkg.sh; fi
  - docker exec "$(cat ${container_id})" pacman -Suy --noconfirm
  - 'docker exec "$(cat ${container_id})" chown -R devel: /aur'
  - docker exec "$(cat ${container_id})" su devel sh -c "cd /aur && makepkg -sri --noconfirm"
  - docker rm -f "$(cat ${container_id})"
